### ISSUE TITLE
Supporting Windows

### ISSUE THREAD

**Issue by Connoropolous** [holochain/lair#34] opened 2021-07-02 00:51 UTC
Based on attempts to bring applications like Snapmail and Acorn out into the wild bundled as Electron apps, we have run in to the requirement that Windows users install wsl2 which is a big technical hurdle for ordinary users. We have been wanting to make these apps available at lower friction. When @ddd-mtl @guillemcordoba and I discussed recently with @zippy it was brought up that this "Unix Domain Socket for Lair" thing might be the main blocker for native Windows support. 

We are thinking about investigating it and seeing what we can do to move this forward. I started a bit of digging and immediately found something interesting, which appears to be that an implementation (if not 100% feature complete) of Unix sockets was brought into Windows 10, with a release in 2017 first to Windows Insider, then it became generally available in version 1809 (aka the October 2018 Update). 
Microsoft open source seems to have published a library that may suit:
https://github.com/Azure/tokio-uds-windows
There's also the Tokio UDS on Windows thread to add:
https://github.com/tokio-rs/tokio/issues/2201
The new Deno language (like nodejs) is also pulling for this clearly. 

Were we collectively unaware of this? I am assuming so, given these lines
https://github.com/holochain/lair/blob/3bd7105108ab241d6719e200dd15905cd3e74da1/crates/lair_keystore_api/src/internal/ipc.rs#L11-L19
and the comments in
https://github.com/holochain/lair/blob/3bd7105108ab241d6719e200dd15905cd3e74da1/crates/lair_keystore_api/src/internal/ipc/win_ipc.rs#L1

The original post is here, from 2017
https://devblogs.microsoft.com/commandline/af_unix-comes-to-windows/
But there's more relevant comments here
https://github.com/microsoft/WSL/issues/4240

I found looking at this commit which referred to that issue gave a bit of insight
https://github.com/MisterDA/ocaml/commit/5855ce5ffd931a2802d5b9a5b2987ab0b276fd0a

https://github.com/holochain/lair/blob/3bd7105108ab241d6719e200dd15905cd3e74da1/.github/workflows/ops.test.yml#L14-L15

@thedavidmeister @neonphog

**Comment by ddd-mtl** [comment] 2021-07-02 01:19
I was planning on looking into it this month.
The problem is with tokio since UnixStreams dont compile on windows. The
fix is to add support for TcpStreams which can we used on windows,
regardless of version.

**Comment by Connoropolous** [comment] 2021-07-02 01:23
I see, so you think it's a better solution to add it (do you estimate it to be more work?) because it adds broader compatibility?

**Comment by ddd-mtl** [comment] 2021-07-02 01:28
Also because Lair is supposed to work over TCP anyway. So it's a 2 birds
one stone solution.

**Comment by Connoropolous** [comment] 2021-07-02 01:32
Cool cool. That's good and there might be one additional prospect here which is that UDP works on both mac/linux/windows AND you can select for via config to use TCP. 
UnixStream for windows for tokio was implemented here by Microsoft devs themselves, so could be used:
https://github.com/Azure/tokio-uds-windows

3 birds with 2 stones?

**Comment by ddd-mtl** [comment] 2021-07-02 01:41
Oh that's cool. Should be easier to use that to start with. A recent win10
version was already required for WSL anyway.

**Comment by Connoropolous** [comment] 2021-07-02 01:48
my thoughts exactly

**Comment by neonphog** [comment] 2021-07-02 15:02
@Connoropolous @ddd-mtl - I hadn't been intending to introduce TCP to lair because of security concerns, although we could discuss it.

The original intention was to use [tokio-named-pipes](https://crates.io/crates/tokio-named-pipes) on windows.

**Comment by Connoropolous** [comment] 2021-07-05 06:01
Oh, I see. Different stories going around here then.

Sounds like the named pipes solution would be the number 1 preference for you @neonphog ?

It seems to be folded right into tokio nowadays:
https://docs.rs/tokio/1.8.0/tokio/net/windows/named_pipe/index.html

**Comment by neonphog** [comment] 2021-07-05 15:09
@Connoropolous 

> It seems to be folded right into tokio nowadays:
> https://docs.rs/tokio/1.8.0/tokio/net/windows/named_pipe/index.html

Oh nice, I hadn't realized that, awesome!

> Sounds like the named pipes solution would be the number 1 preference for you @neonphog ?

Yeah, if this is part of core tokio, let's do that to start, and see if it covers our use-cases. It eliminates a whole set of concerns if we can guarantee only local processes have access, and can [apply os security](https://docs.rs/tokio/1.8.0/tokio/net/windows/named_pipe/struct.ServerOptions.html#method.create_with_security_attributes_raw).

**Comment by Connoropolous** [comment] 2021-07-05 15:31
@neonphog 
I'm glad it's a good surprise. Can you confirm a rough outline of the work @neonphog ?

My guess is that it involves writing in the `win_rpc.rs` file equivalent implementations of:
`IpcRead`, `IpcWrite`, `ipc_connect`, and `IpcServer` from `unix_ipc.rs`

Is UnixStream completely abstracted out?

**Comment by neonphog** [comment] 2021-07-05 15:58
@Connoropolous 

> My guess is that it involves writing in the `win_rpc.rs` file equivalent implementations of:
> `IpcRead`, `IpcWrite`, `ipc_connect`, and `IpcServer` from `unix_ipc.rs`
> 
> Is UnixStream completely abstracted out?

You got it. `IpcRead` must implement `tokio::io::AsyncRead`, `IpcWrite` `tokio::io::AsyncWrite`, and `ipc_connect` / `IpcServer` should have the same signatures. They're switched out at compile time with config directives [here](https://github.com/holochain/lair/blob/main/crates/lair_keystore_api/src/internal/ipc.rs#L11-L19).

**Comment by ddd-mtl** [comment] 2021-07-05 21:51
Actually TCP was my extrapolation for the Holo use-case and the lair-shim thing, but now I see I could be totally wrong so nevermind the TcpStream solution I mentionned.

**Comment by Connoropolous** [comment] 2021-07-05 21:57
@ddd-mtl I have access to Windows on a laptop here dual booted from a Mac, so I can co-code, or also run and compile code you write, etc. Any preferences? :)

**Comment by thedavidmeister** [comment] 2021-07-13 13:57
this looks like a good thing that is happening here, but i don't have much to add so i'm taking myself off notifications :)

**Comment by neonphog** [comment] 2021-07-21 16:47
`v0.0.1-alpha.13` [keystore](https://crates.io/crates/lair_keystore/0.0.1-alpha.13) / [api](https://crates.io/crates/lair_keystore_api/0.0.1-alpha.13) / [client](https://crates.io/crates/lair_keystore_client/0.0.1-alpha.13) published with https://github.com/holochain/lair/pull/37 included. Closing this -- feel free to re-open if there's anything remaining to be addressed.

**Closed by neonphog** 2021-07-21 16:47 UTC
